[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.9"
ic-cdk = "0.11.0"
ic-stable-structures = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
